//created on: 4/03/2016
package co.com.jhilton.drools.descuentos.rules

//list any import classes here.
import java.util.List
import co.com.jhilton.drools.descuentos.model.*
import co.com.jhilton.drools.descuentos.ejecutor.CreditoPreaprobado


//declare any global variables here
global List COLA_CORREOS

rule "descuento por compra con tarjeta debito"
    when
        $f : Factura(formaPago == FormaPago.DEBITO)
    then
    	System.out.println("Se concedió descuento de 2% ");
    	$f.setDescuentoAplicado(0.02);
end

rule "descuento por compra con tarjeta credito"
    when
        $f : Factura(formaPago == FormaPago.CREDITO)
    then
    	System.out.println("Se concedió descuento de 5%");
    	$f.setDescuentoAplicado(0.05);
end

rule "descuento por compra con efectivo"
    when
        $f : Factura(formaPago == FormaPago.EFECTIVO)
    then
    	System.out.println("No se concedió descuento");
    	$f.setDescuentoAplicado(0.0);
end

rule "ingresar preaprobacion credito"
    when
        $f : Factura(formaPago == FormaPago.EFECTIVO, subtotal >= 1000000)
    then
    	System.out.println("Credito preaprobado");
    	CreditoPreaprobado credito = new CreditoPreaprobado($f.getCliente(), $f.getTotal() * 0.80);
    	insert(credito);
end

rule "cliente con credito preaprobado"
    when
        $c : CreditoPreaprobado()
    then
    	System.out.println("Ingresando a la cola");
    	COLA_CORREOS.add($c);
end
